services:
    app:
        build: .
        container_name: simple-app
        volumes:
            - ./demo-app:/var/www/docker-app

    web:
        image: nginx:latest
        container_name: simple-nginx
        ports:
            - "8055:80"
        volumes:
            - ./demo-app:/var/www/docker-app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
