services:
    app:
        build: .
        container_name: simple-app
        volumes:
            - ./demo-app:/var/www/docker-app
        depends_on:
            - db_service
        networks:
            - custom_network
    web:
        image: nginx:latest
        container_name: simple-nginx
        ports:
            - "8055:80"
        volumes:
            - ./demo-app:/var/www/docker-app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - custom_network
    # db_service:
    #     image: postgres:latest
    #     container_name: postgres_db
    #     restart: always
    #     environment:
    #         POSTGRES_USER: myuser
    #         POSTGRES_PASSWORD: mypassword
    #         POSTGRES_DB: mydatabase
    #     ports:
    #         - "5432:5432"
    #     volumes:
    #         - db_data:/var/lib/postgresql/data
    #     networks:
    #         - custom_network
    db_service:
        image: mysql:latest
        container_name: simple-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: demo_db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - custom_network
    redis:
        image: redis:latest
        container_name: simple-redis
        ports:
            - "6379:6379"
        networks:
            - custom_network
volumes:
    db_data:

networks:
    custom_network:
