services:
    app:
        build: .
        container_name: simple-app
        volumes:
            - ./demo-app:/var/www/docker-app
        depends_on:
            - mysql_host
    web:
        image: nginx:latest
        container_name: simple-nginx
        ports:
            - "8055:80"
        volumes:
            - ./demo-app:/var/www/docker-app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
    mysql_host:
        image: mysql:latest
        container_name: simple-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: demo_db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:

networks:
    custom_network:
